//$emailConfig = require_once "../../config/email_config.php";
<?php

require_once "../../config/cors.php";
require_once "../../config/database.php";

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require "../../PHPMailer/Exception.php";
require "../../PHPMailer/PHPMailer.php";
require "../../PHPMailer/SMTP.php";

try {

    $salesStmt = $pdo->query("
        SELECT
            COUNT(*) AS total_orders,
            IFNULL(SUM(grand_total),0) AS total_sales
        FROM orders
        WHERE DATE(created_at)=CURDATE()
        AND order_status='COMPLETED'
    ");

    $sales = $salesStmt->fetch(PDO::FETCH_ASSOC);

    $itemStmt = $pdo->query("
        SELECT
            i.item_name,
            SUM(oi.quantity) AS qty
        FROM order_items oi
        JOIN items i
        ON oi.item_id=i.item_id
        JOIN orders o
        ON oi.order_id=o.order_id
        WHERE DATE(o.created_at)=CURDATE()
        GROUP BY i.item_id
        ORDER BY qty DESC
        LIMIT 5
    ");

    $items = $itemStmt->fetchAll(PDO::FETCH_ASSOC);

    $mail = new PHPMailer(true);

    $mail->isSMTP();

    $mail->Host = "smtp.gmail.com";

    $mail->SMTPAuth = true;
    $emailConfig = require_once "../../config/email_config.php";

    $mail->Username = $emailConfig['smtp_email'];
    $mail->Password = $emailConfig['smtp_password'];

    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;

    $mail->Port = 587;

    $mail->setFrom(
        "bmananya2006@gmail.com",
        "V2 CAFE"
    );

    $mail->addAddress(
        "bmananya2006@gmail.com"
    );

    $mail->isHTML(true);

    $mail->Subject =
        "Today's Sales Report";
            $body = "

    <h2>V2 CAFE - Daily Sales Report</h2>

    <hr>

    <h3>Summary</h3>

    <p><b>Total Orders :</b> {$sales['total_orders']}</p>

    <p><b>Total Sales :</b> ₹ {$sales['total_sales']}</p>

    <hr>

    <h3>Top Selling Items</h3>

    <table border='1' cellpadding='8' cellspacing='0' style='border-collapse:collapse;'>

        <tr>

            <th>Item</th>

            <th>Quantity Sold</th>

        </tr>

    ";

    foreach($items as $item){

        $body .= "

        <tr>

            <td>{$item['item_name']}</td>

            <td>{$item['qty']}</td>

        </tr>

        ";

    }

    $body .= "

    </table>

    <br>

    <p>This is an automated report generated by <b>V2 CAFE Management System</b>.</p>

    ";

    $mail->Body = $body;

    $mail->send();

    echo json_encode([

        "success" => true,

        "message" => "Report emailed successfully."

    ]);

}
catch(Exception $e){

    echo json_encode([

        "success" => false,

        "message" => $mail->ErrorInfo

    ]);

}
?>